#ifndef BOSSHAZARDADAPTIVEENGINE_UTILITIES_H
#define BOSSHAZARDADAPTIVEENGINE_UTILITIES_H

#include <iostream>

uint32_t roundDownToPowerOf2(uint32_t num);

#endif // BOSSHAZARDADAPTIVEENGINE_UTILITIES_H
