#ifndef BOSSHAZARDADAPTIVEENGINE_UTILITIES_HPP
#define BOSSHAZARDADAPTIVEENGINE_UTILITIES_HPP

#include <iostream>

uint32_t roundDownToPowerOf2(uint32_t num);

#endif // BOSSHAZARDADAPTIVEENGINE_UTILITIES_HPP
